name: "CD"

on:
  push:
    branches: [ "main" ]
  merge:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    - name: Vite Github Pages Deployer
      uses: skywarth/vite-github-pages-deployer@v1.3.0